import { Header } from '../../components/layout/Header'
import { Card, CardBody } from '../../components/ui/Card'
import { useDamayanEvents, useMyDamayanAssessments } from '../../hooks/useDamayan'
import { useCurrency } from '../../hooks/useCurrency'
import { formatDate } from '../../lib/utils'

const statusColors: Record<string, string> = {
  pending: 'bg-yellow-100 text-yellow-800',
  paid:    'bg-green-100 text-green-800',
  waived:  'bg-gray-100 text-gray-600',
}

export function DamayanPage() {
  const { format: currency } = useCurrency()
  const { data: events = [] } = useDamayanEvents()
  const { data: assessments = [], isLoading } = useMyDamayanAssessments()

  // Build a lookup map: event_id -> event
  const eventMap = Object.fromEntries(events.map(e => [e.id, e]))

  const pending = assessments.filter(a => a.status === 'pending')
  const history = assessments.filter(a => a.status !== 'pending')

  const totalPending = pending.reduce((s, a) => s + a.amount_due, 0)

  return (
    <div>
      <Header title="Damayan" subtitle="Mutual aid fund — your assessments and contributions" />

      <div className="p-4 sm:p-6 space-y-6">
        {/* Summary */}
        <div className="grid grid-cols-2 gap-3">
          <div className="bg-white rounded-xl border border-gray-200 p-3 sm:p-4">
            <p className="text-xs text-gray-500 mb-1">Pending Assessments</p>
            <p className="text-lg font-semibold text-yellow-700">{pending.length}</p>
          </div>
          <div className="bg-white rounded-xl border border-gray-200 p-3 sm:p-4">
            <p className="text-xs text-gray-500 mb-1">Total Due</p>
            <p className="text-lg font-semibold text-gray-900">{currency(totalPending)}</p>
          </div>
        </div>

        {/* Pending assessments */}
        {pending.length > 0 && (
          <div>
            <h2 className="text-base font-semibold text-gray-900 mb-3">Pending Payments</h2>
            <div className="space-y-2">
              {pending.map(a => {
                const event = eventMap[a.event_id]
                return (
                  <div key={a.id} className="bg-white rounded-xl border border-yellow-200 px-4 py-3.5 flex items-center justify-between gap-3">
                    <div className="flex-1 min-w-0">
                      <p className="font-semibold text-sm text-gray-900 truncate">{event?.title ?? 'Damayan Event'}</p>
                      <p className="text-xs text-gray-400 mt-0.5">
                        {event ? formatDate(event.event_date) : ''}
                      </p>
                    </div>
                    <div className="flex items-center gap-2 flex-shrink-0">
                      <p className="text-sm font-bold text-yellow-700">{currency(a.amount_due)}</p>
                      <span className={`inline-flex px-2 py-0.5 rounded-full text-xs font-medium ${statusColors[a.status]}`}>
                        {a.status}
                      </span>
                    </div>
                  </div>
                )
              })}
            </div>
            <p className="mt-2 text-xs text-gray-400">Contact your cooperative staff to record your payment.</p>
          </div>
        )}

        {/* Assessment history */}
        <div>
          <h2 className="text-base font-semibold text-gray-900 mb-3">Assessment History</h2>
          {isLoading ? (
            <p className="text-sm text-gray-400">Loading…</p>
          ) : assessments.length === 0 ? (
            <Card>
              <CardBody className="py-10 text-center">
                <p className="text-sm text-gray-500">You have no damayan assessments yet.</p>
                <p className="text-xs text-gray-400 mt-1">Assessments are generated by cooperative staff when a damayan event is created.</p>
              </CardBody>
            </Card>
          ) : history.length === 0 ? (
            <p className="text-sm text-gray-400">No completed assessments yet.</p>
          ) : (
            <div className="space-y-2">
              {history.map(a => {
                const event = eventMap[a.event_id]
                return (
                  <div key={a.id} className="bg-white rounded-xl border border-gray-200 px-4 py-3 flex items-center justify-between gap-3">
                    <div className="flex-1 min-w-0">
                      <p className="text-sm font-medium text-gray-900 truncate">{event?.title ?? 'Damayan Event'}</p>
                      <p className="text-xs text-gray-400 mt-0.5">
                        {event ? formatDate(event.event_date) : ''}
                        {a.paid_at ? ` · Paid ${formatDate(a.paid_at)}` : ''}
                      </p>
                    </div>
                    <div className="flex items-center gap-2 flex-shrink-0">
                      <p className="text-sm font-semibold text-gray-700">{currency(a.amount_due)}</p>
                      <span className={`inline-flex px-2 py-0.5 rounded-full text-xs font-medium ${statusColors[a.status]}`}>
                        {a.status}
                      </span>
                    </div>
                  </div>
                )
              })}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
